version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /myspace/app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - api
      - client
    ports:
      - "3030:80"
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /myspace/app/node_modules
      - ./client:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WDS_SOCKET_PORT=0
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /myspace/app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379